/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eliotlash.particlelib;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
//    @Test void testSomeLibraryMethod() {
//        Settings classUnderTest = new Settings();
//        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
//    }
}
