/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eliotlash.particlelib;

import com.eliotlash.particlelib.mcwrapper.IBlock;
import com.eliotlash.particlelib.mcwrapper.ResourceLocation;

import java.util.function.Function;

public class Settings {
    private static boolean particleSorting = false;

    public static boolean getParticleSorting() {
        return particleSorting;
    }

    public static void setParticleSorting(boolean particleSorting) {
        Settings.particleSorting = particleSorting;
    }

    private static Function<ResourceLocation, IBlock> blockLookupImpl;

    /**
     * Set a function that takes a ResourceLocation and looks up a block in the registry, returning the Block instance.
     * This MUST be set before trying to load a particle system.
     * @param blockLookupImpl The lookup function. For Forge 1.12 this can be `ForgeRegistries.BLOCKS::getValue`
     */
    public static void setBlockLookupImpl(Function<ResourceLocation, IBlock> blockLookupImpl) {
        Settings.blockLookupImpl = blockLookupImpl;
    }
    public static IBlock blockLookup(ResourceLocation location) {
        if(blockLookupImpl == null) {
            throw new java.lang.IllegalStateException("Block lookup function must be set by caller using Settings.setBlockLookupImpl before trying to load a particle system.");
        }
        return blockLookupImpl.apply(location);
    }
}
